### ISSUE TITLE
UDEV rules to fix/mitigate the minute+ delay of media switch-out.

### ISSUE THREAD

**Issue by tinwhisker** [roiyz/PiVidBox#1]
It may be worth trying UDEV rules if possible, using add/remove to start/kill OMX player.
Whilst I use a similar script for backups, I'll prefix this with:
"this is crude, isn't tested and could probably be optimised."

Create a rules file: /etc/udev/rules.d/PiVidBox.rules  (You may need to change to 99-PiVidBox.rules, but it should behave the same.)
Add:
```
ENV{DEVTYPE}=="partition", RUN+="/home/pi/mediaevent.sh add", ENV{REMOVE_CMD}="/home/pi/mediaevent.sh remove"
```

(Alternatively, if the above fails)
```
ACTION=="add", KERNEL=="sd*[!0-9]", RUN+="/home/pi/mediaevent.sh add"
ACTION=="remove", KERNEL=="sd*[!0-9]", RUN+="/home/pi/mediaevent.sh remove"
```
In the /home/pi/mediaevent.sh script:
```
#!/bin/sh
if [ $1 == "add" ]
then
  # Call run.sh outside of the udev daemon to prevent timeout.
  echo /home/pi/run.sh | at now
elif [ $1 == "remove" ]
then
  processId=$(ps -ef | grep 'OMXPlayer' | grep -v 'grep' | awk '{ printf $2 }')
  kill -9 $processId
fi
```

chmod +x the scripts.
If the existing unmount script is too slow, just add this after the 'kill' line:
```
  umount -l /media/pi
  rm -R /media/pi
```

**Comment by tinwhisker** [comment]
Quick Edit:

It needs an 'action' to prevent it running multiple times per event.

`ENV{DEVTYPE}=="partition", ACTION=="add", RUN+="/home/pi/mediaevent.sh add", ENV{REMOVE_CMD}="/home/pi/mediaevent.sh remove"`

or in my case (because the partition isn't standard)

`SUBSYSTEM=="block", ACTION=="add", RUN+="/home/pi/mediaevent.sh add", ENV{REMOVE_CMD}="/home/pi/mediaevent.sh remove"`

**Comment by roiyz** [comment]
Sorry for not replying earlier. This looks like great and I'll consider adding. Thanks!
