### ISSUE TITLE
run.sh modification and instructions fix

### ISSUE THREAD

**Issue by mwallred** [roiyz/PiVidBox#2]
First off, thanks for this. It has made life a lot easier for my wife when has to take a presentation somewhere. Just plug and play, so to speak!

I believe you meant for the log/output files to be the same in all three places in the script, based on the fact that in the first instance you are creating a new file and the next two you are appending to an existing file. For mine I also modified the file name to something more specific just to make sure nothing else overwrites it.

#!/bin/bash
OIFS="$IFS"
IFS=$'\n'
echo "starting" > /tmp/run_sh_log.txt
sleep 2
while true
do
  for file in `find /media/pi -type f \( -iname \*.avi -o -iname \*.mp4 \) | shuf`
    do
      echo "$file"
      echo "$file" >>/tmp/run_sh_log.txt
      /usr/bin/omxplayer --adev hdmi --aspect-mode stretch --threshold 5 $file
    done
  echo "Completed cycle" >>/tmp/run_sh_log.txt
  sleep 10
done

In your instructions, the chown command should be using chmod instead. Like so:

chmod +x /home/pi/run.sh

**Comment by mwallred** [comment]
Sorry, I didn't realize it would take away the formatting.

**Comment by roiyz** [comment]
Thanks for finding this issue and sorry for the late reply
Fixed
